/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vista;

import com.controladores.CRUDS.CRUDCategoria;
import com.modelo.Categoria;
import java.util.ArrayList;

/**
 *
 * @author dylan
 */
public class AddProductoInventarioGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddProductoInventarioGUI
     */
    public AddProductoInventarioGUI() {
        initComponents();
        mostrarCategorias();
    }
    
    public void mostrarCategorias(){
        CRUDCategoria CRUDcat = new CRUDCategoria();
        ArrayList<Categoria> listaCategorias = CRUDcat.getCategorias();
        
        cbxCategoria.removeAllItems();
        
        for (int i = 0; i < listaCategorias.size(); i++) {
            cbxCategoria.addItem(new Categoria(listaCategorias.get(i).getId(), listaCategorias.get(i).getDescripcion()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bttCancelarInventario = new javax.swing.JButton();
        bttAddInventario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoProductoInventario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNombreProductoInventario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadProductoInventario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValorProductoInventario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(0, 102, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AÑADIR PRODUCTO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        bttCancelarInventario.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        bttCancelarInventario.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\11450177.png")); // NOI18N
        bttCancelarInventario.setText("Cancelar");
        bttCancelarInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttCancelarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarInventarioActionPerformed(evt);
            }
        });
        jPanel4.add(bttCancelarInventario);

        bttAddInventario.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        bttAddInventario.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\4303945.png")); // NOI18N
        bttAddInventario.setText("Aceptar");
        bttAddInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAddInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddInventarioActionPerformed(evt);
            }
        });
        jPanel4.add(bttAddInventario);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 4, 4));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Codigo del producto");
        jPanel1.add(jLabel1);

        txtCodigoProductoInventario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.add(txtCodigoProductoInventario);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Categoria del producto");
        jPanel1.add(jLabel3);

        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCategoria);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Nombre del producto");
        jPanel1.add(jLabel5);
        jPanel1.add(txtNombreProductoInventario);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad del producto");
        jPanel1.add(jLabel6);
        jPanel1.add(txtCantidadProductoInventario);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Valor unitario del producto");
        jPanel1.add(jLabel2);

        txtValorProductoInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorProductoInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorProductoInventario);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel9.setText("PLACITA EL MONO");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\3194591.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\1147934.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(63, 63, 63)
                .addComponent(jLabel8)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorProductoInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorProductoInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorProductoInventarioActionPerformed

    private void bttAddInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttAddInventarioActionPerformed

    private void bttCancelarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttCancelarInventarioActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductoInventarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductoInventarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductoInventarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductoInventarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductoInventarioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bttAddInventario;
    public javax.swing.JButton bttCancelarInventario;
    public javax.swing.JComboBox<Categoria> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JTextField txtCantidadProductoInventario;
    public javax.swing.JTextField txtCodigoProductoInventario;
    public javax.swing.JTextField txtNombreProductoInventario;
    public javax.swing.JTextField txtValorProductoInventario;
    // End of variables declaration//GEN-END:variables
}
