/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vista;

import com.controladores.CRUDS.CRUDCategoria;
import com.modelo.Categoria;
import java.util.ArrayList;

/**
 *
 * @author dylan
 */
public class ModificarProductoInventario extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProductoInventario
     */
    public ModificarProductoInventario() {
        initComponents();
        mostrarCategorias();
    }
    
    public void mostrarCategorias(){
        CRUDCategoria CRUDcat = new CRUDCategoria();
        ArrayList<Categoria> listaCategorias = CRUDcat.getCategorias();
        
        cbxCategoriaModificarInventario.removeAllItems();
        
        for (int i = 0; i < listaCategorias.size(); i++) {
            cbxCategoriaModificarInventario.addItem(new Categoria(listaCategorias.get(i).getId(), listaCategorias.get(i).getDescripcion()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoNuevoProductoInventario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxCategoriaModificarInventario = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNombreProductoInventario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadProductoInventario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVisibilidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValorProductoInventario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoProductoAntiguo = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bttCancelar = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        bttAceptar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 4, 4));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Codigo nuevo del producto ");
        jPanel1.add(jLabel1);

        txtCodigoNuevoProductoInventario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.add(txtCodigoNuevoProductoInventario);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Categoria del producto");
        jPanel1.add(jLabel3);

        jPanel1.add(cbxCategoriaModificarInventario);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Nombre del producto");
        jPanel1.add(jLabel5);
        jPanel1.add(txtNombreProductoInventario);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad del producto");
        jPanel1.add(jLabel6);
        jPanel1.add(txtCantidadProductoInventario);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Visibilidad");
        jPanel1.add(jLabel4);
        jPanel1.add(txtVisibilidad);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Valor unitario del producto");
        jPanel1.add(jLabel2);

        txtValorProductoInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorProductoInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorProductoInventario);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Codigo antiguo del producto");
        jPanel1.add(jLabel8);
        jPanel1.add(txtCodigoProductoAntiguo);

        jPanel8.setBackground(new java.awt.Color(0, 102, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MODIFICAR PRODUCTO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        bttCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bttCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\11450177.png")); // NOI18N
        bttCancelar.setText("Cancelar");
        bttCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(bttCancelar);

        bttBuscar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bttBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\1265907.png")); // NOI18N
        bttBuscar.setText("Buscar");
        bttBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(bttBuscar);

        bttAceptar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bttAceptar.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\4303945.png")); // NOI18N
        bttAceptar.setText("Aceptar");
        bttAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(bttAceptar);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel9.setText("PLACITA EL MONO");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\3194591.png")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documents\\NetBeansProjects\\StockWave_V2\\src\\main\\java\\com\\imagenes\\1147934.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorProductoInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorProductoInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorProductoInventarioActionPerformed

    private void bttAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProductoInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bttAceptar;
    public javax.swing.JButton bttBuscar;
    public javax.swing.JButton bttCancelar;
    public javax.swing.JComboBox<Categoria> cbxCategoriaModificarInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JTextField txtCantidadProductoInventario;
    public javax.swing.JTextField txtCodigoNuevoProductoInventario;
    public javax.swing.JTextField txtCodigoProductoAntiguo;
    public javax.swing.JTextField txtNombreProductoInventario;
    public javax.swing.JTextField txtValorProductoInventario;
    public javax.swing.JTextField txtVisibilidad;
    // End of variables declaration//GEN-END:variables
}
